name: Postgres.app
description: "Postgres.app is the easiest way to get started with PostgreSQL on the Mac. Open the app, and you have a PostgreSQL server ready and awaiting new connections. Close the app, and the server shuts down."

downloadLocation: https://github.com/PostgresApp/PostgresApp/releases/download/9.5.1.0/Postgres-9.5.1.0.zip
postgresqlVersion: 9.5.1
postgisVersion: 2.2.1

downloadLocation94: https://github.com/PostgresApp/PostgresApp/releases/download/9.4.6.0/Postgres-9.4.6.0.zip
postgresqlVersion94: 9.4.6
postgisVersion94: 2.1.8

downloadLocation93: https://github.com/PostgresApp/PostgresApp/releases/download/9.3.10.0/Postgres-9.3.10.0.zip
postgresqlVersion93: 9.3.10
postgisVersion93: 2.1.8

languages: [en, de]
