name: Postgres.app
description: "Postgres.app is a full featured PostgreSQL installation packaged as a standard Mac app."

gems: ['jekyll-github-metadata']
repository: postgresapp/postgresapp

downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.1.3/Postgres-2.1.3.dmg"
releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.1.3"
postgresappVersion: "2.1.3"
postgresappMinSystemVersion: "10.10"
postgresqlVersions: [
	{ postgres: "10.3", postgis: "2.4.3" },
	{ postgres: "9.6.8", postgis: "2.3.6" },
	{ postgres: "9.5.12", postgis: "2.2.6" },
]

legacyMinSystemVersion: "10.7"
legacyVersions: [
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.1.3/Postgres-Legacy-9.3.22.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/v2.1.3",
		postgresqlVersion: "9.3.22",
		postgisVersion: "2.1.9",
	},
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.1.3/Postgres-Legacy-9.4.17.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/v2.1.3",
		postgresqlVersion: "9.4.17",
		postgisVersion: "2.1.9",
	},
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.1.3/Postgres-Legacy-9.5.12.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/v2.1.3",
		postgresqlVersion: "9.5.12",
		postgisVersion: "2.2.6",
	},
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.1.3/Postgres-Legacy-9.6.8.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/v2.1.3",
		postgresqlVersion: "9.6.8",
		postgisVersion: "2.3.6",
	},
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.1.3/Postgres-Legacy-10.3.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/v2.1.3",
		postgresqlVersion: "10.3",
		postgisVersion: "2.4.3",
	},
]

languages: [en, de]

strings: {
	de: {
		subtitle: Der schnellste Weg zu PostgreSQL am Mac,
		download-button: Download,
		docs-button: Dokumentation,
		github-button: Github,
		stars: Sterne,
		follow: Folge,
		find-us: Finde uns auf,
		typo: "Feler gefunden?",
		edit-page: Bearbeite diese Seite,
	},
	en: {
		subtitle: The easiest way to get started with PostgreSQL on the Mac,
		download-button: Download,
		docs-button: Documentation,
		github-button: Github,
		stars: Stars,
		follow: Follow,
		find-us: Find us on,
		typo: "Spotted a typo?",
		edit-page: edit this page,
	}
}