name: Postgres.app
description: "Postgres.app is a full featured PostgreSQL installation packaged as a standard Mac app."

gems: ['jekyll-github-metadata']
repository: postgresapp/postgresapp

downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.0.2/Postgres-2.0.2.dmg"
releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.0.2/"
postgresappVersion: "2.0.2"
postgresappMinSystemVersion: "10.10"
postgresqlVersions: [
	{ postgres: "9.6.2", postgis: "2.3.2" },
	{ postgres: "9.5.6", postgis: "2.2.5" },
]

legacyMinSystemVersion: "10.7"
legacyVersions: [
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/9.3.16/Postgres-9.3.16.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/9.3.16/",
		postgresqlVersion: "9.3.16",
		postgisVersion: "2.1.8",
	},
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/9.4.11/Postgres-9.4.11.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/9.4.11/",
		postgresqlVersion: "9.4.11",
		postgisVersion: "2.1.8",
	},
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/9.5.6/Postgres-9.5.6.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/9.5.6/",
		postgresqlVersion: "9.5.6",
		postgisVersion: "2.2.5",
	},
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/9.6.2/Postgres-9.6.2.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/9.6.2/",
		postgresqlVersion: "9.6.2",
		postgisVersion: "2.3.2",
	},
]

languages: [en, de]

strings: {
	de: {
		subtitle: Der schnellste Weg zu PostgreSQL am Mac,
		download-button: Download,
		docs-button: Dokumentation,
		github-button: Github,
		stars: Sterne,
		follow: Folge,
		find-us: Finde uns auf,
		typo: "Feler gefunden?",
		edit-page: Bearbeite diese Seite,
	},
	en: {
		subtitle: The easiest way to get started with PostgreSQL on the Mac,
		download-button: Download,
		docs-button: Documentation,
		github-button: Github,
		stars: Stars,
		follow: Follow,
		find-us: Find us on,
		typo: "Spotted a typo?",
		edit-page: edit this page,
	}
}