name: Postgres.app
description: "Postgres.app is a full featured PostgreSQL installation packaged as a standard Mac app."

plugins:
  - jekyll-redirect-from
  - jekyll-github-metadata

repository: postgresapp/postgresapp

release: {
	name: {
		en: "Postgres.app with PostgreSQL 12", 
		de: "Postgres.app mit PostgreSQL 12",
	},
	size: "70MB",
	downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.3.5/Postgres-2.3.5-12.dmg",
	releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.3.5",
	postgresappVersion: "2.3.5",
	postgresappMinSystemVersion: "10.12",
	postgresqlVersions: [
		{ postgres: "12.3", postgis: "3.0.1", plv8: "2.3.14" },
	],
}

extraReleases: [
	{
		name: {
			en: "Postgres.app with PostgreSQL 10, 11 and 12", 
			de: "Postgres.app mit PostgreSQL 10, 11 und 12",
		},
		size: "180MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.3.5/Postgres-2.3.5-10-11-12.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.3.5",
		postgresappVersion: "2.3.5",
		postgresappMinSystemVersion: "10.12",
		postgresqlVersions: [
			{ postgres: "12.3", postgis: "3.0.1", plv8: "2.3.14" },
			{ postgres: "11.8", postgis: "2.5.4", plv8: "2.3.14" },
			{ postgres: "10.13", postgis: "2.4.8", plv8: "1.4.8" },
		],
	},
	{
		name: {
			en: "Postgres.app with all currently supported PostgreSQL versions", 
			de: "Postgres.app mit allen PostgreSQL Versionen",
		},
		size: "320MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.3.5/Postgres-2.3.5-9.4-9.5-9.6-10-11-12.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.3.5",
		postgresappVersion: "2.3.5",
		postgresappMinSystemVersion: "10.12",
		postgresqlVersions: [
			{ postgres: "12.3", postgis: "3.0.1", plv8: "2.3.14" },
			{ postgres: "11.8", postgis: "2.5.4", plv8: "2.3.14" },
			{ postgres: "10.13", postgis: "2.4.8", plv8: "1.4.8" },
			{ postgres: "9.6.18", postgis: "2.3.10", plv8: "1.4.8" },
			{ postgres: "9.5.22", postgis: "2.2.8", plv8: "1.4.8" },
			{ postgres: "9.4.26", postgis: "2.1.9", plv8: "1.4.8" },
		],
	},
]

legacyReleases: [
	{
		name: {
			en: "Postgres.app with PostgreSQL 9.5, 9.6 and 10", 
			de: "Postgres.app mit PostgreSQL 9.5, 9.6 und 10",
		},
		size: "156MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.2.5/Postgres-2.1.9.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/tag/v2.2.5",
		postgresappVersion: "2.1.9",
		postgresappMinSystemVersion: "10.10",
		postgresqlVersions: [
			{ postgres: "10.10", postgis: "2.4.7", plv8: "1.4.8" },
			{ postgres: "9.6.15", postgis: "2.3.9", plv8: "1.4.8" },
			{ postgres: "9.5.19", postgis: "2.2.8", plv8: "1.4.8" },
		],
	},
	{
		name: {
			en: "Legacy Postgres.app with PostgreSQL 10", 
			de: "Legacy Postgres.app mit PostgreSQL 10",
		},
		size: "65MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.2.5/Postgres-Legacy-10.10.zip",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/tag/v2.2.5",
		postgresappMinSystemVersion: "10.7",
		postgresqlVersions: [
			{ postgres: "10.10", postgis: "2.4.7", plv8: "1.4.8" },
		],
	},
	{
		name: {
			en: "Legacy Postgres.app with PostgreSQL 9.6", 
			de: "Legacy Postgres.app mit PostgreSQL 9.6",
		},
		size: "49MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.2.5/Postgres-Legacy-9.6.15.zip",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/tag/v2.2.5",
		postgresappMinSystemVersion: "10.7",
		postgresqlVersions: [
			{ postgres: "9.6.15", postgis: "2.3.9", plv8: "1.4.8" },
		],
	},
	{
		name: {
			en: "Legacy Postgres.app with PostgreSQL 9.5", 
			de: "Legacy Postgres.app mit PostgreSQL 9.5",
		},
		size: "44MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.2.5/Postgres-Legacy-9.5.19.zip",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/tag/v2.2.5",
		postgresappMinSystemVersion: "10.7",
		postgresqlVersions: [
			{ postgres: "9.5.19", postgis: "2.2.8", plv8: "1.4.8" },
		],
	},
	{
		name: {
			en: "Legacy Postgres.app with PostgreSQL 9.4", 
			de: "Legacy Postgres.app mit PostgreSQL 9.4",
		},
		size: "41MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.2.5/Postgres-Legacy-9.4.24.zip",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/tag/v2.2.5",
		postgresappMinSystemVersion: "10.7",
		postgresqlVersions: [
			{ postgres: "9.4.24", postgis: "2.1.9", plv8: "1.4.8" },
		],
	},
	{
		name: {
			en: "Legacy Postgres.app with PostgreSQL 9.3", 
			de: "Legacy Postgres.app mit PostgreSQL 9.3",
		},
		size: "41MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.1.4/Postgres-Legacy-9.3.23.zip",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/tag/v2.1.4",
		postgresappMinSystemVersion: "10.7",
		postgresqlVersions: [
			{ postgres: "9.3.23", postgis: "2.1.9", plv8: "1.4.8" },
		],
	},
]

languages: [en, de]

strings: {
	de: {
		subtitle: Der schnellste Weg zu PostgreSQL am Mac,
		homepage-button: Einleitung,
		downloads-title: Downloads,
		download-button: Laden,
		docs-button: Dokumentation,
		github-button: GitHub,
		stars: Sterne,
		follow: Folge,
		find-us: Finde uns auf,
		typo: "Feler gefunden?",
		edit-page: Bearbeite diese Seite,
		requires-os: "Benötigt",
		download-size: "Downloadgröße",
	},
	en: {
		subtitle: The easiest way to get started with PostgreSQL on the Mac,
		homepage-button: Introduction,
		downloads-title: Downloads,
		download-button: Download,
		docs-button: Documentation,
		github-button: GitHub,
		stars: Stars,
		follow: Follow,
		find-us: Find us on,
		typo: "Spotted a typo?",
		edit-page: edit this page,
		requires-os: "Requires",
		download-size: "Download Size",
	}
}
