name: Postgres.app
description: "Postgres.app is the easiest way to get started with PostgreSQL on the Mac. Open the app, and you have a PostgreSQL server ready and awaiting new connections. Close the app, and the server shuts down."

downloadLocation: https://github.com/PostgresApp/PostgresApp/releases/download/9.6.0/Postgres-9.6.0.zip
postgresqlVersion: 9.6.0
postgisVersion: 2.3.0

downloadLocation93: https://github.com/PostgresApp/PostgresApp/releases/download/9.3.14.1/Postgres-9.3.14.1.zip
postgresqlVersion93: 9.3.14
postgisVersion93: 2.1.8

downloadLocation94: https://github.com/PostgresApp/PostgresApp/releases/download/9.4.9.1/Postgres-9.4.9.1.zip
postgresqlVersion94: 9.4.9
postgisVersion94: 2.1.8

downloadLocation95: https://github.com/PostgresApp/PostgresApp/releases/download/9.5.4.2/Postgres-9.5.4.2.zip
postgresqlVersion95: 9.5.4
postgisVersion95: 2.2.2

downloadLocation96: https://github.com/PostgresApp/PostgresApp/releases/download/9.6.0/Postgres-9.6.0.zip
postgresqlVersion96: 9.6.0
postgisVersion96: 2.3.0


languages: [en, de]
