name: Postgres.app
description: "Postgres.app is a full featured PostgreSQL installation packaged as a standard Mac app."

gems: ['jekyll-github-metadata']
repository: postgresapp/postgresapp

downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.0.4/Postgres-2.0.4.dmg"
releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.0.4/"
postgresappVersion: "2.0.4"
postgresappMinSystemVersion: "10.10"
postgresqlVersions: [
	{ postgres: "9.6.4", postgis: "2.3.3" },
	{ postgres: "9.5.8", postgis: "2.2.5" },
]

legacyMinSystemVersion: "10.7"
legacyVersions: [
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/9.3.18/Postgres-9.3.18.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/9.3.18/",
		postgresqlVersion: "9.3.18",
		postgisVersion: "2.1.8",
	},
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/9.4.13/Postgres-9.4.13.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/9.4.13/",
		postgresqlVersion: "9.4.13",
		postgisVersion: "2.1.8",
	},
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/9.5.7/Postgres-9.5.8.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/9.5.8/",
		postgresqlVersion: "9.5.8",
		postgisVersion: "2.2.5",
	},
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/9.6.4/Postgres-9.6.4.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/9.6.4/",
		postgresqlVersion: "9.6.4",
		postgisVersion: "2.3.3",
	},
]

languages: [en, de]

strings: {
	de: {
		subtitle: Der schnellste Weg zu PostgreSQL am Mac,
		download-button: Download,
		docs-button: Dokumentation,
		github-button: Github,
		stars: Sterne,
		follow: Folge,
		find-us: Finde uns auf,
		typo: "Feler gefunden?",
		edit-page: Bearbeite diese Seite,
	},
	en: {
		subtitle: The easiest way to get started with PostgreSQL on the Mac,
		download-button: Download,
		docs-button: Documentation,
		github-button: Github,
		stars: Stars,
		follow: Follow,
		find-us: Find us on,
		typo: "Spotted a typo?",
		edit-page: edit this page,
	}
}